spring.application.name=java-easy-bank
# Server
server.port=8080
# Database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=java_easy_bank;encrypt=false;trustServerCertificate=true
spring.datasource.username=john
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Jackson
spring.jackson.time-zone=Asia/Taipei
#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false